"""add learning tables: quiz_question, quiz_session, user_progress

Revision ID: 8365584c75b4
Revises: aa7ee03fec43
Create Date: 2026-09-30 10:33:12.798868
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8365584c75b4'
down_revision: Union[str, None] = 'aa7ee03fec43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('AKSARA', 'UNGGAH_UNGGUH', name='questioncategory'), nullable=False),
    sa.Column('difficulty', sa.Enum('MUDAH', 'SEDANG', 'SULIT', name='questiondifficulty'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(length=200), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_question_category'), 'quiz_question', ['category'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_identifier', sa.String(length=128), nullable=False),
    sa.Column('category', sa.Enum('AKSARA', 'UNGGAH_UNGGUH', name='questioncategory'), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('last_studied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_progress_user_category', 'user_progress', ['user_identifier', 'category'], unique=True)
    op.create_index(op.f('ix_user_progress_user_identifier'), 'user_progress', ['user_identifier'], unique=True)
    op.create_table('quiz_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_identifier', sa.String(length=128), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_answer', sa.String(length=200), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_session_question_id'), 'quiz_session', ['question_id'], unique=False)
    op.create_index(op.f('ix_quiz_session_user_identifier'), 'quiz_session', ['user_identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_session_user_identifier'), table_name='quiz_session')
    op.drop_index(op.f('ix_quiz_session_question_id'), table_name='quiz_session')
    op.drop_table('quiz_session')
    op.drop_index(op.f('ix_user_progress_user_identifier'), table_name='user_progress')
    op.drop_index('ix_user_progress_user_category', table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_quiz_question_category'), table_name='quiz_question')
    op.drop_table('quiz_question')
    # ### end Alembic commands ###
