"""add soft delete fields to kawruh and paribasan

Revision ID: aa7ee03fec43
Revises: 20260930_0004
Create Date: 2026-09-30 10:01:55.383894
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'aa7ee03fec43'
down_revision: Union[str, None] = '20260930_0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_training_dataset', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('ai_training_dataset', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_ai_kategori'), table_name='ai_training_dataset')
    op.drop_index(op.f('idx_ai_verified'), table_name='ai_training_dataset')
    op.drop_table_comment(
        'ai_training_dataset',
        existing_comment='Dataset prompt-completion untuk fine-tuning LLM kebahasaan Jawa',
        schema=None
    )
    op.alter_column('aksara_jawa', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_aksara_jenis'), table_name='aksara_jawa')
    op.drop_index(op.f('idx_aksara_latin'), table_name='aksara_jawa')
    op.drop_table_comment(
        'aksara_jawa',
        existing_comment='Referensi aksara Jawa: carakan, pasangan, sandhangan, murda, swara, rekan, pada',
        schema=None
    )
    op.add_column('kawruh_basa', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('kawruh_basa', 'kelas_kata',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'Tembung Aran'::character varying"))
    op.alter_column('kawruh_basa', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_kawruh_basa_status'), table_name='kawruh_basa')
    op.drop_index(op.f('idx_kawruh_indonesia_trgm'), table_name='kawruh_basa', postgresql_ops={'bahasa_indonesia': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_kawruh_krama_inggil_trgm'), table_name='kawruh_basa', postgresql_ops={'krama_inggil': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_kawruh_krama_lugu_trgm'), table_name='kawruh_basa', postgresql_ops={'krama_lugu': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_kawruh_ngoko_trgm'), table_name='kawruh_basa', postgresql_ops={'ngoko': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_table_comment(
        'kawruh_basa',
        existing_comment='Kamus padanan kata: ngoko, krama lugu, krama inggil, bahasa Indonesia',
        schema=None
    )
    op.alter_column('macapat', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_table_comment(
        'macapat',
        existing_comment='Paugeran 11 tembang macapat: guru gatra, wilangan, dan lagu per gatra (JSONB)',
        schema=None
    )
    op.add_column('paribasan', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('paribasan', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_paribasan_kategori'), table_name='paribasan')
    op.drop_index(op.f('idx_paribasan_status'), table_name='paribasan')
    op.drop_index(op.f('idx_paribasan_text_trgm'), table_name='paribasan', postgresql_ops={'teks': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_table_comment(
        'paribasan',
        existing_comment='Paribasan, bebasan, dan saloka beserta tegese',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'paribasan',
        'Paribasan, bebasan, dan saloka beserta tegese',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_paribasan_text_trgm'), 'paribasan', ['teks'], unique=False, postgresql_ops={'teks': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_paribasan_status'), 'paribasan', ['status'], unique=False)
    op.create_index(op.f('idx_paribasan_kategori'), 'paribasan', ['kategori'], unique=False)
    op.alter_column('paribasan', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('paribasan', 'deleted_at')
    op.create_table_comment(
        'macapat',
        'Paugeran 11 tembang macapat: guru gatra, wilangan, dan lagu per gatra (JSONB)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('macapat', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'kawruh_basa',
        'Kamus padanan kata: ngoko, krama lugu, krama inggil, bahasa Indonesia',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_kawruh_ngoko_trgm'), 'kawruh_basa', ['ngoko'], unique=False, postgresql_ops={'ngoko': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_kawruh_krama_lugu_trgm'), 'kawruh_basa', ['krama_lugu'], unique=False, postgresql_ops={'krama_lugu': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_kawruh_krama_inggil_trgm'), 'kawruh_basa', ['krama_inggil'], unique=False, postgresql_ops={'krama_inggil': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_kawruh_indonesia_trgm'), 'kawruh_basa', ['bahasa_indonesia'], unique=False, postgresql_ops={'bahasa_indonesia': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_kawruh_basa_status'), 'kawruh_basa', ['status'], unique=False)
    op.alter_column('kawruh_basa', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('kawruh_basa', 'kelas_kata',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'Tembung Aran'::character varying"))
    op.drop_column('kawruh_basa', 'deleted_at')
    op.create_table_comment(
        'aksara_jawa',
        'Referensi aksara Jawa: carakan, pasangan, sandhangan, murda, swara, rekan, pada',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_aksara_latin'), 'aksara_jawa', ['latin_equivalent'], unique=False)
    op.create_index(op.f('idx_aksara_jenis'), 'aksara_jawa', ['jenis'], unique=False)
    op.alter_column('aksara_jawa', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'ai_training_dataset',
        'Dataset prompt-completion untuk fine-tuning LLM kebahasaan Jawa',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_ai_verified'), 'ai_training_dataset', ['is_verified'], unique=False)
    op.create_index(op.f('idx_ai_kategori'), 'ai_training_dataset', ['kategori'], unique=False)
    op.alter_column('ai_training_dataset', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ai_training_dataset', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
